import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyOrder" model, go to https://bambe-crm-app.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Order",
  fields: {
    autoWrite: {
      type: "boolean",
      default: false,
      storageKey: "WF9jdF-lE09t",
    },
    shopifyShop: {
      type: "belongsTo",
      parent: { model: "shopifyShop" },
      storageKey: "jV9n9w9ddBkG",
    },
    writeOrder: {
      type: "boolean",
      default: false,
      storageKey: "zmUxDbQrRPpm",
    },
  },
  shopify: {
    fields: [
      "additionalFees",
      "billingAddress",
      "browserIp",
      "buyerAcceptsMarketing",
      "cancelReason",
      "cancellation",
      "cancelledAt",
      "cartToken",
      "checkoutToken",
      "clientDetails",
      "closedAt",
      "currency",
      "customer",
      "customerLocale",
      "discountApplications",
      "discountCodes",
      "email",
      "estimatedTaxes",
      "financialStatus",
      "fulfillmentOrders",
      "fulfillmentStatus",
      "fulfillments",
      "landingSite",
      "name",
      "note",
      "noteAttributes",
      "orderStatusUrl",
      "paymentGatewayNames",
      "presentmentCurrency",
      "processedAt",
      "processingMethod",
      "shippingAddress",
      "shop",
      "sourceName",
      "subtotalPrice",
      "subtotalPriceSet",
      "tags",
      "taxLines",
      "taxesIncluded",
      "test",
      "totalDiscounts",
      "totalDiscountsSet",
      "totalLineItemsPrice",
      "totalLineItemsPriceSet",
      "totalOutstanding",
      "totalPrice",
      "totalPriceSet",
      "totalTax",
      "totalTaxSet",
      "totalTipReceived",
      "totalWeight",
    ],
  },
};
